CLASS /dmo/bp_bookingsupplement_u20 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /dmo/i_travel_u20 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /dmo/bp_bookingsupplement_u20 IMPLEMENTATION.
ENDCLASS.
